############################################# DATASET PREPARATION #############################################

dataset_name: 'paraquat_window_3200_overlapt_1600_binsize_4' # Name of the dataset

###################### Specifications ######################
window_size: '3200'       # Size of genomic windows that serve as input
window_overlap: '1600'    # Size of overlap between windows
genome_length: '4641652'
mincount: '10000'         # Minimal amount of spacers per bamfile. Lower get filtered out.
gene_perc: '15'           # Percent of lowest expressed genes (spacer count over all bam files) to get filtered out. windows that contain those genes get filtered out
binsize: '4'             # Binsize to bin coverage profiles (should be a power of 2)
bam_batchsize: '5'       # Size of batches of .bam files to be processed together (depends on memory, decrease batchsize if you process more windows per file)
bamfile_start: 'S'       # Start of bam file names
###################### Files ######################
input_directory_reads: '/cluster/scratch/hugifl/' # Directory with bam files
input_directory_annotation: '../spacer_coverage_input/'
output_directory: '/cluster/home/hugifl/spacer_coverage_output/' 
data_output_directory: '/cluster/scratch/hugifl/spacer_coverage_final_data/'

gene_file: 'ECOCYC_genes.txt'   # File from ECOCYC with gene start and end sites and further info
promoter_file: 'ECOCYC_promoters.txt'     # File from ECOCYC with promoter absolute + 1 positions
terminator_file: 'ECOCYC_terminators.txt'     # File from ECOCYC with terminator start and end sites
genome_fasta: 'U00096.3.fasta'  # Genome sequence in .fasta format
count_matrix: 'genomeCounts_UMI_paraquat2.txt' # Matrix with spacer counts per gene per fasta file for normalization purposes
bam_files: 'genomeBams_paraquat/'  # Spacer alignment .bam files
